app/accounts/urls.py
from django.contrib.auth.views import login, logout
from django.urls import path, re_path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.DashbBoardView.as_view(), name='dashboard'),
    path('entrar/', login, {'template_name': 'accounts/login.html'}, name='login'),
    path('sair/', logout, {'next_page': 'accounts:dashboard'}, name='logout'),

    path('cadastre-se/', views.register, name='register'),
    path('nova-senha/', views.password_reset, name='password_reset'),
    re_path('confirmar-nova-senha/(?P<key>\w+)/', views.password_reset_confirm, name='password_reset_confirm'),
    path('perfil/', views.UserProfileUpdate.as_view(), name='profile'),

    path('cadastros/revisores/', views.ReviewerListView.as_view(), name='reviewer_index'),
    path('cadastros/revisores/adicionar/', views.ReviewerCreateView.as_view(), name='reviewer_create'),
    path('cadastros/revisores/<int:pk>/atualizar/', views.ReviewerUpdateView.as_view(), name='reviewer_update'),
    path('cadastros/revisores/<int:pk>/apagar/', views.ReviewerDeleteView.as_view(), name='reviewer_delete'),
]

app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.accounts.urls', namespace="accounts")),
    path('cadastros/', include('app.registers.urls', namespace="registers")),
    path('admin/', admin.site.urls),
    path('api/', include('app.api.urls')),
]

# media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/accounts/models.py
import os

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models

from django.urls import reverse
from django.utils.timezone import now


def get_upload_path(instance, filename):
    return os.path.join('account/photos/', now().date().strftime("%Y/%m/%d"), filename)


class User(AbstractUser):
    """
    AbstractUser Class to extend User Model
    """
    photo = models.ImageField(upload_to=get_upload_path, blank=True, verbose_name='Foto')
    name = models.CharField('Nome', max_length=100, blank=True)
    is_reviewer = models.BooleanField('É revisor?', default=False)
    can_review = models.BooleanField('Pode revisar?', default=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.name or self.username

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'


class PasswordReset(models.Model):
    """
    Reset UserPassword Model
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='Usuário',
        related_name='resets', on_delete=models.CASCADE
    )
    key = models.CharField('Chave', max_length=100, unique=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    confirmed = models.BooleanField('Confirmado?', default=False, blank=True)

    def __str__(self):
        return '{0} em {1}'.format(self.user, self.created_at)

    class Meta:
        verbose_name = 'Nova senha'
        verbose_name_plural = 'Novas senhas'
        ordering = ['-created_at']

app/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.db import transaction

from app.core.mail import send_mail_template
from app.core.mixins import ReadOnlyFieldsMixin
from app.core.utils import generate_hash_key
from .models import PasswordReset, User


class PasswordResetForm(forms.Form):
    email = forms.EmailField(label='E-mail')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            return email
        raise forms.ValidationError(
            'Nenhum usuário encontrado com este e-mail'
        )

    def save(self):
        user = User.objects.get(email=self.cleaned_data['email'])
        key = generate_hash_key(user.username)
        reset = PasswordReset(key=key, user=user)
        reset.save()
        template_name = 'accounts/password_reset_mail.html'
        subject = 'Criar nova senha Mangue Digital'
        context = {
            'reset': reset,
        }
        send_mail_template(subject, template_name, context, [user.email])


class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Confirmação de Senha', widget=forms.PasswordInput
    )

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('A confirmação não está correta')
        return password2

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'email']


class UserForm(ReadOnlyFieldsMixin, forms.ModelForm):
    readonly_fields = ('username',)

    class Meta:
        model = User
        fields = ['username', 'email', 'photo']


class ReviewerFormCreate(forms.ModelForm):
    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Confirmação de Senha', widget=forms.PasswordInput
    )

    class Meta:
        model = User
        fields = ['name', 'username', 'password1', 'password2', 'email', 'can_review', 'photo']

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('A confirmação não está correta')
        return password2

    def clean_email(self):
        email = self.cleaned_data['email']

        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Este email já está em uso.")
        return email

    def save(self, commit=True):
        user = super(ReviewerFormCreate, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.is_reviewer = True
            user.save()
        return user


class ReviewerFormUpdate(ReadOnlyFieldsMixin, forms.ModelForm):
    readonly_fields = ('username',)

    class Meta:
        model = User
        fields = ['name', 'username', 'email', 'can_review', 'photo']

    def clean_email(self):
        email = self.cleaned_data['email']

        if User.objects.filter(email=email).exclude(username=self.instance.username).exists():
            raise forms.ValidationError("Este email já está em uso.")
        return email

app/accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import TemplateView, UpdateView, CreateView, DeleteView, ListView

from app.core.mixins import get_context_pagination
from app.registers.models import Review
from .forms import *
from .models import *


class DashbBoardView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/dashboard.html'

    reviews_paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(DashbBoardView, self).get_context_data(**kwargs)

        users = User.objects.filter(is_reviewer=True).order_by('-created_at')
        reviews = Review.objects.all().order_by('-created_at')

        if self.request.user.is_reviewer:
            reviews = Review.objects.filter(reviewer=self.request.user).order_by('-created_at')

        reviews_page_obj = get_context_pagination(
            self.request, "reviews_page", reviews, self.reviews_paginate_by
        )

        context['reviews_num'] = reviews.count()
        context['reviewers_num'] = users.count()
        context['reviews'] = reviews_page_obj

        return context


def register(request):
    template = 'accounts/register.html'
    context = {}
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                username=user.username, password=form.cleaned_data['password1']
            )
            messages.success(
                request, 'Registro realizado com sucesso.'
            )
            login(request, user)
            return redirect('accounts:login')
    else:
        form = RegisterForm()
    context['form'] = form
    return render(request, template, context)


def password_reset(request):
    template_name = 'accounts/password_reset.html'
    context = {}
    form = PasswordResetForm(request.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form
    return render(request, template_name, context)


def password_reset_confirm(request, key):
    template_name = 'accounts/password_reset_confirm.html'
    context = {}
    reset = get_object_or_404(PasswordReset, key=key)
    form = SetPasswordForm(user=reset.user, data=request.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form
    return render(request, template_name, context)


@login_required
def edit_password(request):
    template = 'accounts/profile_edit_password.html'
    context = {}
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            messages.success(
                request, 'Sua senha foi alterada com sucesso. '
                         'Por favor faça um novo acesso com a senha atualizada.'
            )
            return redirect('accounts:profile_detail', request.user.pk)

    else:
        form = PasswordChangeForm(user=request.user)
    context['form'] = form
    return render(request, template, context)


class UserProfileUpdate(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'accounts/profile.html'
    context_object_name = 'user'
    form_class = UserForm
    success_url = reverse_lazy('accounts:dashboard')

    def get_object(self):
        return self.request.user


label = 'Revisores'
warning_message = 'Você não tem permissão para gerenciar ' + label.lower() + "."


class ReviewerListView(LoginRequiredMixin, ListView):
    template_name = 'accounts/reviewers/index.html'
    paginate_by = 10
    ordering = ['-date_joined']

    def get_queryset(self):
        queryset = User.objects.filter(is_reviewer=True).order_by('-date_joined')
        return queryset

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_reviewer:
            messages.warning(request, warning_message)
            return redirect('accounts:dashboard')
        return super(self.__class__, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)

        context["label"] = label
        context["note_empty"] = 'Nenhum ' + label + ' cadastrado.'

        return context


class ReviewerCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = User
    template_name = 'accounts/reviewers/add.html'
    form_class = ReviewerFormCreate
    success_message = "Adicionado com sucesso."

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_reviewer:
            messages.warning(request, warning_message)
            return redirect('accounts:dashboard')
        return super(self.__class__, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)

        context["label"] = label

        return context

    def form_valid(self, form):
        user = form.save()
        return redirect('accounts:reviewer_index')


class ReviewerUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    template_name = 'accounts/reviewers/edit.html'
    form_class = ReviewerFormUpdate
    success_url = reverse_lazy('accounts:reviewer_index')
    success_message = "Atualizado com sucesso."

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_reviewer:
            messages.warning(request, warning_message)
            return redirect('accounts:dashboard')
        return super(self.__class__, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)

        context["label"] = label

        return context


class ReviewerDeleteView(LoginRequiredMixin, DeleteView):
    model = User
    template_name = 'core_admin/confirm_delete.html'
    success_url = reverse_lazy('accounts:reviewer_index')
    success_message = "Removida com sucesso."

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_reviewer:
            messages.warning(request, warning_message)
            return redirect('accounts:dashboard')
        return super(self.__class__, self).dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(ReviewerDeleteView, self).delete(request, *args, **kwargs)

app/accounts/templates/accounts/reviewers/_table.html
{% load static helper bootstrap_pagination %}
<div class="table-responsive m-t-20">
    <table class="table stylish-table">
        <thead>
        <tr>
            <th>Usuário</th>
            <th>Email</th>
            <th>Pode Revisar</th>
            <th class="text-nowrap">Ação</th>
        </tr>
        </thead>
        <tbody>
        {% for item in object_list %}
            <tr>
                <td>{{ item.username }}</td>
                <td>{{ item.email }}</td>

                <td>
                    {% if item.can_review %}Sim{% else %}Não{% endif %}
                </td>

                <td style="width:90px;" class="">
                    <div class="btn-group btn-group-sm" role="group">
                        <a class="btn btn-secondary" href="{% url 'accounts:reviewer_update' item.pk %}"
                           data-toggle="tooltip"
                           title=""
                           data-original-title="Editar"><i class="fa fa-pencil-square-o"></i></a>
                        <a class="btn btn-secondary btn-sm" href="{% url 'accounts:reviewer_delete' item.pk %}" title=""
                           data-toggle="tooltip"
                           data-original-title="Apagar"><i class="fa fa-trash-o"></i></a>
                    </div>
                </td>

            </tr>
        {% empty %}
            <tr>
                <td colspan="8">{{ note_empty }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if page_obj %}
        {% bootstrap_paginate page_obj url_param_name=paramname range=10 align='center' previous_label="<i class='fa fa-angle-double-left'></i>" next_label="<i class='fa fa-angle-double-right'></i>" %}
    {% endif %}

</div>

app/accounts/templates/accounts/reviewers/add.html
{% extends 'core_admin/base_admin.html' %}
{% load static %}

{% block page-content-title %}Adicionar{% endblock %}

{% block page-content-breadcrumb %}{{ block.super }}
    | <a href="{% url 'accounts:dashboard' %}">{{ label }}</a> | Adicionar: {{ label }}
{% endblock %}

{% block page-content %}
    <div class="row">
        <div class="col-sm-8">
            <div class="card card-default">
                <div class="card-block">

                    {% include 'core_admin/_form.html' with button_submit='Salvar' %}

                </div>
            </div>
        </div>
    </div>

{% endblock %}



{% block admin_styles %}{{ block.super }}

    {% include 'core_admin/styles.html' %}

{% endblock %}

{% block admin_js %}{{ block.super }}
    {{ form.media }}

    {% include 'core_admin/scripts.html' %}

{% endblock %}

app/accounts/templates/accounts/reviewers/edit.html
{% extends 'core_admin/base_admin.html' %}
{% load static %}

{% block page-content-title %}Editar: {{ object }}{% endblock %}

{% block page-content-breadcrumb %}{{ block.super }}
    | <a href="{% url 'accounts:reviewer_index' %}">{{ label }}</a> | Editar: {{ object }}
{% endblock %}

{% block page-content %}
    <div class="row">
        <div class="col-sm-8">
            <div class="card card-default">
                <div class="card-block">

                    {% include 'core_admin/_form.html' with button_submit='Atualizar' %}

                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block admin_styles %}{{ block.super }}

    {% include 'core_admin/styles.html' %}

{% endblock %}

{% block admin_js %}{{ block.super }}
    {{ form.media }}

    {% include 'core_admin/scripts.html' %}

{% endblock %}

app/accounts/templates/accounts/reviewers/index.html
{% extends 'core_admin/base_admin.html' %}
{% load static %}
{% block page_content_class %}items-list-page{% endblock %}


{% block page-content-title %}{{ label }}{% endblock %}
{% block page-content-breadcrumb %}{{ block.super }}
    | {{ label }}
{% endblock %}

{% block page-title-right %}
    <div class="items-search">
        <a class="btn btn-primary btn-sm" href="{% url 'accounts:reviewer_create' %}">
            <i class="fa fa-plus"></i> Adicionar
        </a>
    </div>
{% endblock %}

{% block page-content %}

    <div class="row">
        <div class="col-lg-12">
            <div class="card">

                <div class="card-block">
                    <div class="card-title-block">
                        <h3 class="title"> Lista de {{ label }} </h3>
                    </div>
                    {% include 'accounts/reviewers/_table.html' with object_list=object_list page_obj=page_obj paramname='page' note_empty=note_empty %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(function () {

            setTimeout(function () {
                if ($(".alert").is(":visible")) {
                    $(".alert").fadeOut("slow");
                }
            }, 3000)

        });
    </script>

{% endblock %}