app/accounts/urls.py
from django.contrib.auth.views import login, logout
from django.urls import path, re_path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.DashbBoardView.as_view(), name='dashboard'),
    path('entrar/', login, {'template_name': 'accounts/login.html'}, name='login'),
    path('sair/', logout, {'next_page': 'accounts:dashboard'}, name='logout'),

    path('cadastre-se/', views.register, name='register'),
    path('nova-senha/', views.password_reset, name='password_reset'),
    re_path('confirmar-nova-senha/(?P<key>\w+)/', views.password_reset_confirm, name='password_reset_confirm'),
    path('perfil/', views.UserProfileUpdate.as_view(), name='profile'),

    path('cadastros/revisores/', views.ReviewerListView.as_view(), name='reviewer_index'),
    path('cadastros/revisores/adicionar/', views.ReviewerCreateView.as_view(), name='reviewer_create'),
    path('cadastros/revisores/<int:pk>/atualizar/', views.ReviewerUpdateView.as_view(), name='reviewer_update'),
    path('cadastros/revisores/<int:pk>/apagar/', views.ReviewerDeleteView.as_view(), name='reviewer_delete'),
]

app/registers/urls.py
from django.contrib.auth.views import login, logout
from django.urls import path

app_name = 'registers'

from . import views

urlpatterns = [
    path('empresas/', views.CompanyListView.as_view(), name='company_index'),
    path('empresas/adicionar/', views.CompanyCreateView.as_view(), name='company_create'),
    path('empresas/<int:pk>/atualizar/', views.CompanyUpdateView.as_view(), name='company_update'),
    path('empresas/<int:pk>/apagar/', views.CompanyDeleteView.as_view(), name='company_delete'),

    path('revisoes/', views.ReviewListView.as_view(), name='review_index'),
    path('revisoes/adicionar/', views.ReviewCreateView.as_view(), name='review_create'),
    path('revisoes/<int:pk>/atualizar/', views.ReviewUpdateView.as_view(), name='review_update'),
    path('revisoes/<int:pk>/apagar/', views.ReviewDeleteView.as_view(), name='review_delete'),

]

app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.accounts.urls', namespace="accounts")),
    path('cadastros/', include('app.registers.urls', namespace="registers")),
    path('admin/', admin.site.urls),
    path('api/', include('app.api.urls')),
]

# media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/models.py
from django.db import models

# Create your models here.

app/core/views.py
from django.shortcuts import render

# Create your views here.

app/core/templates/core_admin/includes/_form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
            {{ error }}
        {% endfor %}
    </div>
{% endif %}


{% for field in form.visible_fields %}


    {% if field|field_type == 'modelmultiplechoicefield' %}

        <div class="form-group">

            <h5 class="box-title">{{ field.label_tag }}</h5>

            {% render_field field id="pre-selected-options" %}

        </div>

    {% elif field|field_type == 'booleanfield' or field|field_type == 'multiplechoicefield' %}

        <div class="demo-checkbox">

            {% if field|field_type == 'multiplechoicefield' %}

                {{ field.label_tag }}

                {% for choice_id, choice_label in field.field.choices %}
                    <input type="checkbox" name="{{ field.label }}" value="{{ choice_id }}" id="{{ choice_id }}">
                    <label for="{{ choice_id }}">{{ choice_label }}</label>
                {% endfor %}

            {% else %}
                {% render_field field %}
                <label for="{{ field.auto_id }}">{{ field.label }}</label>
            {% endif %}

        </div>

    {% elif field|field_type == 'typedchoicefield' %}

        <div class="form-group">

            {{ field.label_tag }}
            {% render_field field class="custom-select" %}

        </div>

    {% else %}
        <div class="form-group {% if field.errors %}has-error{% endif %}">
            {{ field.label_tag }}

            {% if form.is_bound %}
                {% if field.errors %}
                    {% render_field field class="form-control boxed" %}
                    {% for error in field.errors %}
                        <span class="has-error">
                            {{ error }}
                        </span>
                    {% endfor %}
                {% else %}
                    {% render_field field class="form-control" %}
                {% endif %}
            {% else %}
                {% render_field field class="form-control" %}
            {% endif %}

            {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
        </div>

    {% endif %}


{% endfor %}

app/core/templates/core_admin/includes/_menu.html
{% load static %}
<nav class="menu">

    <ul class="sidebar-menu metismenu" id="sidebar-menu">
        <li>
            <a href="{% url 'accounts:dashboard' %}">
                <i class="fa fa-home"></i> Painel </a>
        </li>

        {% if request.user.is_superuser %}

            <li>
                <a href="#">
                    <i class="fa fa-th-large"></i> Cadastros
                    <i class="fa arrow"></i>
                </a>
                <ul class="sidebar-nav">

                    <li>
                        <a href="{% url 'accounts:reviewer_index' %}"> Revisor </a>
                    </li>
                    <li>
                        <a href="{% url 'registers:company_index' %}"> Empresas </a>
                    </li>

                </ul>
            </li>

        {% endif %}
    </ul>
</nav>

app/core/templates/core_admin/includes/_sidebar.html
{% load static thumbnail %}
<aside class="sidebar">
    <div class="sidebar-container">
        <div class="sidebar-header">
            <div class="brand">
                <img width="140" src="{% static 'core_admin/images/onidata-logo-w.png' %}" alt="Onidata">

            </div>
        </div>
        {% include 'core_admin/includes/_menu.html' %}
    </div>

</aside>
<div class="sidebar-overlay" id="sidebar-overlay"></div>
<div class="sidebar-mobile-menu-handle" id="sidebar-mobile-menu-handle"></div>
<div class="mobile-menu-handle"></div>

app/core/templates/core_admin/includes/_topbar.html
{% load static thumbnail %}
{% block topbar %}
    <header class="header">
        <div class="header-block header-block-collapse d-lg-none d-xl-none">
            <button class="collapse-btn" id="sidebar-collapse-btn">
                <i class="fa fa-bars"></i>
            </button>
        </div>


        <div class="header-block header-block-nav">
            {% block profile %}
                {% if request.user.is_authenticated %}
                    <ul class="nav-profile">


                        {% block profile_dropdown %}

                            <li class="profile dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                                   aria-haspopup="true" aria-expanded="false">
                                    {% if request.user.photo %}
                                        <div class="img"
                                             style="background-image: url('{{ request.user.photo|thumbnail_url:'avatar' }}')"></div>
                                    {% else %}
                                        <div class="img"
                                             style="background-image: url('{% static 'core_admin/images/profile.png' %}')"></div>
                                    {% endif %}
                                    <span class="name"> {{ request.user.name|default:request.user.username }} </span>
                                </a>
                                <div class="dropdown-menu profile-dropdown-menu" aria-labelledby="dropdownMenu1">
                                    <a class="dropdown-item" href="{% url 'accounts:profile' %}">
                                        <i class="fa fa-user icon"></i> Perfil </a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{% url 'accounts:logout' %}">
                                        <i class="fa fa-power-off icon"></i> Sair </a>
                                </div>
                            </li>
                        {% endblock %}
                    </ul>
                {% endif %}
            {% endblock %}
        </div>
    </header>
{% endblock %}