app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.accounts.urls', namespace="accounts")),
    path('cadastros/', include('app.registers.urls', namespace="registers")),
    path('admin/', admin.site.urls),
    path('api/', include('app.api.urls')),
]

# media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/accounts/models.py
import os

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models

from django.urls import reverse
from django.utils.timezone import now


def get_upload_path(instance, filename):
    return os.path.join('account/photos/', now().date().strftime("%Y/%m/%d"), filename)


class User(AbstractUser):
    """
    AbstractUser Class to extend User Model
    """
    photo = models.ImageField(upload_to=get_upload_path, blank=True, verbose_name='Foto')
    name = models.CharField('Nome', max_length=100, blank=True)
    is_reviewer = models.BooleanField('É revisor?', default=False)
    can_review = models.BooleanField('Pode revisar?', default=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.name or self.username

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'


class PasswordReset(models.Model):
    """
    Reset UserPassword Model
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='Usuário',
        related_name='resets', on_delete=models.CASCADE
    )
    key = models.CharField('Chave', max_length=100, unique=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    confirmed = models.BooleanField('Confirmado?', default=False, blank=True)

    def __str__(self):
        return '{0} em {1}'.format(self.user, self.created_at)

    class Meta:
        verbose_name = 'Nova senha'
        verbose_name_plural = 'Novas senhas'
        ordering = ['-created_at']

app/core/models.py
from django.db import models

# Create your models here.

app/registers/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.urls import reverse

from app.accounts.models import User


class Company(models.Model):
    """
    Company Model.
    """
    name = models.CharField('Nome', max_length=100)
    email = models.EmailField('E-mail')

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    modified_at = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Empresa'
        verbose_name_plural = 'Empresas'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('registers:company_update', kwargs={'pk': self.pk})


class Review(models.Model):
    """
      Review Model.
    """
    title = models.CharField('Titulo', max_length=100)
    summary = models.TextField('Conteúdo')
    rating = models.PositiveIntegerField('Avaliação', validators=[MinValueValidator(1), MaxValueValidator(5)])
    ip_address = models.GenericIPAddressField('Endereço de IP')
    company = models.ForeignKey(Company, on_delete=models.CASCADE, verbose_name='Empresa')
    reviewer = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Revisor')
    submission_at = models.DateTimeField('Data de submissão', auto_now_add=True)

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    modified_at = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Revisão'
        verbose_name_plural = 'Revisões'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('registers:review_update', kwargs={'pk': self.pk})

app/core/views.py
from django.shortcuts import render

# Create your views here.

app/core/templates/core_admin/_form.html
<form class="form-horizontal" enctype="multipart/form-data" method="post" novalidate>
    {% csrf_token %}
    {% include 'core_admin/includes/_form.html' with form=form %}
    <button type="submit" class="btn btn-primary">{{ button_submit}}</button>
</form>

app/core/templates/core_admin/_form_delete.html
<div class="alert alert-warning">Tem certeza de que deseja excluir <strong>"{{ object }}"</strong> ?</div>


<div class="row">
    <div class="col-lg-12">
        <form method="post">{% csrf_token %}
            <a class="btn btn-secondary" href="{{ request.META.HTTP_REFERER }}">Cancelar</a>
            <input class="btn btn-danger" type="submit" value="Confirmar"/>
        </form>
    </div>

</div>

app/core/templates/core_admin/base_admin.html
<!doctype html>
{% load static %}
<html class="no-js" lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block admin_title %}Admin | Onidata{% endblock %}</title>
    <meta name="description" content="{% block admin_meta_description %}Mangue Digital{% endblock %}">
    <meta name="author" content="{% block admin_meta_author %}Marlon Leite{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block admin_favicon %}
        <link rel="shortcut icon" href="{% static 'core_admin/images/favicons/favicon.ico' %}" type="image/x-icon">
        <link rel="icon" href="{% static 'core_admin/images/favicons/favicon.ico' %}" type="image/x-icon">
    {% endblock %}


    {% block admin_styles %}
        <link rel="stylesheet" href="{% static 'core_admin/vendors/modular-admin/css/vendor.css' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/metismenu/dist/metisMenu.min.css">
        <link rel="stylesheet" id="theme-style" href="{% static 'core_admin/vendors/modular-admin/css/app.css' %}">
        <link rel="stylesheet" id="theme-style"
              href="{% static 'core_admin/vendors/modular-admin/css/app-blue.css' %}">
    {% endblock %}

    <link href="{% static 'core_admin/css/main.min.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="{% block body_class %}{% endblock %}">
<div class="main-wrapper">
    {% block main_wrapper %}
        <div class="app" id="app">
            {% block topbar %}
                {% include 'core_admin/includes/_topbar.html' %}
            {% endblock %}
            {% block sidebar %}
                {% include 'core_admin/includes/_sidebar.html' %}
            {% endblock %}
            {% block  page_wrapper %}

                <article class="content {% block page_content_class %}{% endblock %}">

                    {% block messages %}
                        {% for message in messages %}

                            <div class="alert alert-{{ message.tags }}">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                        aria-hidden="true">×</span></button>
                                {{ message }}
                            </div>

                        {% endfor %}
                    {% endblock %}

                    {% block page-title %}
                        <div class="title-search-block">
                            <div class="title-block">
                                <h1 class="title">{% block page-content-title %}{% endblock %}</h1>
                                <p class="title-description">
                                    {% block page-content-breadcrumb %}
                                        <a href="{% url 'accounts:dashboard' %}">Painel</a>
                                    {% endblock %}
                                </p>
                            </div>
                            {% block page-title-right %}{% endblock %}
                        </div>
                    {% endblock %}


                    {% block subtitle-block %}{% endblock %}
                    {% block page-content %}{% endblock %}

                </article>
                {% block  page_footer %}
                    <footer class="footer">
                        <div class="footer-block author">
                            © {% now 'Y' %} Onidata - Revisões
                        </div>
                    </footer>
                {% endblock %}
                {% block  modal_media %}
                    <div class="modal fade" id="modal-media">
                        <div class="modal-dialog modal-lg">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title">Media Library</h4>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                        <span class="sr-only">Close</span>
                                    </button>
                                </div>
                                <div class="modal-body modal-tab-container">
                                    <ul class="nav nav-tabs modal-tabs" role="tablist">
                                        <li class="nav-item">
                                            <a class="nav-link" href="#gallery" data-toggle="tab" role="tab">Gallery</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link active" href="#upload" data-toggle="tab"
                                               role="tab">Upload</a>
                                        </li>
                                    </ul>
                                    <div class="tab-content modal-tab-content">
                                        <div class="tab-pane fade" id="gallery" role="tabpanel">
                                            <div class="images-container">
                                                <div class="row"></div>
                                            </div>
                                        </div>
                                        <div class="tab-pane fade active in" id="upload" role="tabpanel">
                                            <div class="upload-container">
                                                <div id="dropzone">
                                                    <form action="/" method="POST" enctype="multipart/form-data"
                                                          class="dropzone needsclick dz-clickable" id="demo-upload">
                                                        <div class="dz-message-block">
                                                            <div class="dz-message needsclick"> Drop files here or click
                                                                to
                                                                upload.
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <button type="button" class="btn btn-primary">Insert Selected</button>
                                </div>
                            </div>
                            <!-- /.modal-content -->
                        </div>
                        <!-- /.modal-dialog -->
                    </div>
                    <!-- /.modal -->
                {% endblock %}
                {% block  modal_confirm %}
                    <div class="modal fade" id="confirm-modal">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title">
                                        <i class="fa fa-warning"></i> Alert</h4>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p>Are you sure want to do this?</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-primary" data-dismiss="modal">Yes</button>
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                                </div>
                            </div>
                            <!-- /.modal-content -->
                        </div>
                        <!-- /.modal-dialog -->
                    </div>
                    <!-- /.modal -->
                {% endblock %}
            {% endblock %}
        </div>
    {% endblock %}
</div>


{% block admin_js %}

    <script src="{% static 'core_admin/vendors/modular-admin/js/vendor.js' %}"></script>
    <script src="{% static 'core_admin/vendors/modular-admin/js/app.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/metismenu"></script>
{% endblock %}

{% block js %}{% endblock %}

<script>
    $(document).ready(function () {
        $("body").tooltip({selector: '[data-toggle=tooltip]'});
    });
</script>
</body>
</html>

app/core/templates/core_admin/confirm_delete.html
{% extends 'core_admin/base_admin.html' %}
{% load static %}

{% block page-title %}{% endblock %}

{% block page-content %}

    {% include 'core_admin/_form_delete.html' %}

{% endblock %}

app/core/templates/core_admin/scripts.html
{% load static %}

<script src="{% static 'core_admin/vendors/jquery-mask-plugin/jquery.mask.min.js' %}"></script>
<script src="{% static 'core_admin/js/slugify.js' %}"></script>
<script>
    $(document).ready(function () {

        var PhoneMaskBehavior = function (val) {
                return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
            },
            phoneOption = {
                onKeyPress: function (val, e, field, options) {
                    field.mask(PhoneMaskBehavior.apply({}, arguments), options);
                }
            };

        $('.date').mask('00/00/0000');
        $('.time').mask('00:00:00');
        $('.date_time').mask('00/00/0000 00:00:00');
        $('.cep').mask('00000-000');
        $('.phone').mask(PhoneMaskBehavior, phoneOption);
        $('.cpf').mask('000.000.000-00', {reverse: true});
        $('#id_cnpj').mask('00.000.000/0000-00', {reverse: true});
        $('.money').mask("#.##0,00", {reverse: true});
        $('.percent').mask('##0,00%', {reverse: true});

        $('#id_ip_address').mask('099.099.099.099');

        $("#id_name").c_slugify({slug: "#id_slug", type: "_"});

    });
</script>

app/core/templates/core_admin/styles.html
{% load static %}
<link rel="stylesheet" href="{% static 'core_admin/css/forms.css' %}">