app/registers/urls.py
from django.contrib.auth.views import login, logout
from django.urls import path

app_name = 'registers'

from . import views

urlpatterns = [
    path('empresas/', views.CompanyListView.as_view(), name='company_index'),
    path('empresas/adicionar/', views.CompanyCreateView.as_view(), name='company_create'),
    path('empresas/<int:pk>/atualizar/', views.CompanyUpdateView.as_view(), name='company_update'),
    path('empresas/<int:pk>/apagar/', views.CompanyDeleteView.as_view(), name='company_delete'),

    path('revisoes/', views.ReviewListView.as_view(), name='review_index'),
    path('revisoes/adicionar/', views.ReviewCreateView.as_view(), name='review_create'),
    path('revisoes/<int:pk>/atualizar/', views.ReviewUpdateView.as_view(), name='review_update'),
    path('revisoes/<int:pk>/apagar/', views.ReviewDeleteView.as_view(), name='review_delete'),

]

app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.accounts.urls', namespace="accounts")),
    path('cadastros/', include('app.registers.urls', namespace="registers")),
    path('admin/', admin.site.urls),
    path('api/', include('app.api.urls')),
]

# media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/registers/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.urls import reverse

from app.accounts.models import User


class Company(models.Model):
    """
    Company Model.
    """
    name = models.CharField('Nome', max_length=100)
    email = models.EmailField('E-mail')

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    modified_at = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Empresa'
        verbose_name_plural = 'Empresas'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('registers:company_update', kwargs={'pk': self.pk})


class Review(models.Model):
    """
      Review Model.
    """
    title = models.CharField('Titulo', max_length=100)
    summary = models.TextField('Conteúdo')
    rating = models.PositiveIntegerField('Avaliação', validators=[MinValueValidator(1), MaxValueValidator(5)])
    ip_address = models.GenericIPAddressField('Endereço de IP')
    company = models.ForeignKey(Company, on_delete=models.CASCADE, verbose_name='Empresa')
    reviewer = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Revisor')
    submission_at = models.DateTimeField('Data de submissão', auto_now_add=True)

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    modified_at = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Revisão'
        verbose_name_plural = 'Revisões'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('registers:review_update', kwargs={'pk': self.pk})

app/registers/forms.py
from django import forms
from .models import Company, Review


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = '__all__'


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = '__all__'

app/registers/views/company.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from ..forms import CompanyForm
from ..models import Company

model = Company
form = CompanyForm
label = 'Empresas'
warning_message = 'Você não tem permissão para gerenciar ' + label.lower() + "."


class CompanyListView(LoginRequiredMixin, ListView):
    model = model
    template_name = 'registers/companies/index.html'
    paginate_by = 10
    ordering = ['-created_at']

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_reviewer:
            messages.warning(request, warning_message)
            return redirect('accounts:dashboard')
        return super(self.__class__, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)

        context["label"] = label
        context["note_empty"] = 'Nenhuma ' + label + ' cadastrada.'

        return context


class CompanyCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = model
    template_name = 'registers/companies/add.html'
    form_class = form
    success_url = reverse_lazy('registers:company_index')
    success_message = "Adicionado com sucesso."

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_reviewer:
            messages.warning(request, warning_message)
            return redirect('accounts:dashboard')
        return super(self.__class__, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)

        context["label"] = label

        return context


class CompanyUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = model
    template_name = 'registers/companies/edit.html'
    form_class = form
    success_url = reverse_lazy('registers:company_index')
    success_message = "Atualizado com sucesso."

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_reviewer:
            messages.warning(request, warning_message)
            return redirect('accounts:dashboard')
        return super(self.__class__, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)

        context["label"] = label

        return context


class CompanyDeleteView(LoginRequiredMixin, DeleteView):
    model = model
    template_name = 'core_admin/confirm_delete.html'
    success_url = reverse_lazy('registers:company_index')
    success_message = "Removido com sucesso."

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_reviewer:
            messages.warning(request, warning_message)
            return redirect('accounts:dashboard')
        return super(self.__class__, self).dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(CompanyDeleteView, self).delete(request, *args, **kwargs)

app/registers/views/review.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from ..forms import ReviewForm
from ..models import Review

model = Review
form = ReviewForm
label = 'Revisões'
warning_message = 'Você não tem permissão para gerenciar ' + label.lower() + "."


class ReviewListView(LoginRequiredMixin, ListView):
    model = model
    template_name = 'registers/reviews/index.html'
    paginate_by = 10
    ordering = ['-created_at']

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_reviewer:
            messages.warning(request, warning_message)
            return redirect('accounts:dashboard')
        return super(self.__class__, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)

        context["label"] = label
        context["note_empty"] = 'Nenhuma ' + label + ' cadastrada.'

        return context


class ReviewCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = model
    template_name = 'registers/reviews/add.html'
    form_class = form
    success_url = reverse_lazy('registers:review_index')
    success_message = "Adicionada com sucesso."

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_reviewer:
            messages.warning(request, warning_message)
            return redirect('accounts:dashboard')
        return super(self.__class__, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)

        context["label"] = label

        return context


class ReviewUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = model
    template_name = 'registers/reviews/edit.html'
    form_class = form
    success_url = reverse_lazy('registers:review_index')
    success_message = "Atualizada com sucesso."

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_reviewer:
            messages.warning(request, warning_message)
            return redirect('accounts:dashboard')
        return super(self.__class__, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)

        context["label"] = label

        return context


class ReviewDeleteView(LoginRequiredMixin, DeleteView):
    model = model
    template_name = 'core_admin/confirm_delete.html'
    success_url = reverse_lazy('registers:review_index')
    success_message = "Removida com sucesso."

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_reviewer:
            messages.warning(request, warning_message)
            return redirect('accounts:dashboard')
        return super(self.__class__, self).dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(ReviewDeleteView, self).delete(request, *args, **kwargs)

app/registers/templates/registers/companies/_table.html
{% load static bootstrap_pagination %}
<div class="table-responsive m-t-20">
    <table class="table stylish-table">
        <thead>
        <tr>
            <th>Nome</th>
            <th>Email</th>
            <th>CNPJ</th>
            <th>Data</th>
            <th class="text-nowrap">Ação</th>
        </tr>
        </thead>
        <tbody>
        {% for item in object_list %}
            <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.email }}</td>
                <td>{{ item.cnpj }}</td>
                <td>{{ item.created_at|date }}</td>

                <td style="width:90px;" class="">
                    <div class="btn-group btn-group-sm" role="group">
                        <a class="btn btn-secondary" href="{{ item.get_absolute_url }}" data-toggle="tooltip"
                           title=""
                           data-original-title="Editar"><i class="fa fa-pencil-square-o"></i></a>
                        <a class="btn btn-secondary btn-sm" href="{% url 'registers:company_delete' item.pk %}" title=""
                           data-toggle="tooltip"
                           data-original-title="Apagar"><i class="fa fa-trash-o"></i></a>
                    </div>
                </td>

            </tr>
        {% empty %}
            <tr>
                <td colspan="4">{{ note_empty }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if page_obj %}
        {% bootstrap_paginate page_obj url_param_name=paramname range=10 align='center' previous_label="<i class='fa fa-angle-double-left'></i>" next_label="<i class='fa fa-angle-double-right'></i>" %}
    {% endif %}

</div>

app/registers/templates/registers/companies/add.html
{% extends 'core_admin/base_admin.html' %}
{% load static %}

{% block page-content-title %}Adicionar{% endblock %}

{% block page-content-breadcrumb %}{{ block.super }}
    | <a href="{% url 'registers:company_index' %}">{{ label }}</a> | Adicionar: {{ label }}
{% endblock %}

{% block page-content %}
    <div class="row">
        <div class="col-sm-8">
            <div class="card card-default">
                <div class="card-block">

                    {% include 'core_admin/_form.html' with button_submit='Salvar' %}

                </div>
            </div>
        </div>
    </div>

{% endblock %}



{% block admin_styles %}{{ block.super }}

    {% include 'core_admin/styles.html' %}

{% endblock %}

{% block admin_js %}{{ block.super }}
    {{ form.media }}

    {% include 'core_admin/scripts.html' %}

{% endblock %}

app/registers/templates/registers/companies/edit.html
{% extends 'core_admin/base_admin.html' %}
{% load static %}

{% block page-content-title %}Editar: {{ object }}{% endblock %}

{% block page-content-breadcrumb %}{{ block.super }}
    | <a href="{% url 'registers:company_index' %}">{{ label }}</a> | Editar: {{ object }}
{% endblock %}

{% block page-content %}
    <div class="row">
        <div class="col-sm-8">
            <div class="card card-default">
                <div class="card-block">

                    {% include 'core_admin/_form.html' with button_submit='Atualizar' %}

                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block admin_styles %}{{ block.super }}

    {% include 'core_admin/styles.html' %}

{% endblock %}

{% block admin_js %}{{ block.super }}
    {{ form.media }}

    {% include 'core_admin/scripts.html' %}

{% endblock %}

app/registers/templates/registers/companies/index.html
{% extends 'core_admin/base_admin.html' %}
{% load static %}
{% block page_content_class %}items-list-page{% endblock %}


{% block page-content-title %}{{ label }}{% endblock %}
{% block page-content-breadcrumb %}{{ block.super }}
    | {{ label }}
{% endblock %}

{% block page-title-right %}
    <div class="items-search">
        <a class="btn btn-primary btn-sm" href="{% url 'registers:company_create' %}">
            <i class="fa fa-plus"></i> Adicionar
        </a>
    </div>
{% endblock %}

{% block page-content %}

    <div class="row">
        <div class="col-lg-12">
            <div class="card">

                <div class="card-block">
                    <div class="card-title-block">
                        <h3 class="title"> Lista de {{ label }} </h3>
                    </div>
                    {% include 'registers/companies/_table.html' with object_list=object_list page_obj=page_obj paramname='page' note_empty=note_empty %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(function () {

            setTimeout(function () {
                if ($(".alert").is(":visible")) {
                    $(".alert").fadeOut("slow");
                }
            }, 3000)

        });
    </script>

{% endblock %}